name: Code Quality

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  analyze:
    name: Static Analysis
    runs-on: macos-14
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Select Xcode Version
        run: |
          sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
          
      - name: Resolve Package Dependencies
        run: |
          xcodebuild -resolvePackageDependencies -project StressTool.xcodeproj
          
      - name: Run Static Analysis
        run: |
          xcodebuild analyze \
            -project StressTool.xcodeproj \
            -scheme StressTool \
            -destination 'platform=macOS' \
            -configuration Debug \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            DEVELOPMENT_TEAM="" | xcpretty && exit ${PIPESTATUS[0]}
