name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test StressTool
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Select Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_15.0.app/Contents/Developer || sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
        
      - name: Show Xcode Version
        run: xcodebuild -version
        
      - name: Show Available Schemes
        run: xcodebuild -list -project StressTool.xcodeproj
        
      - name: Build StressTool
        run: |
          xcodebuild clean build \
            -project StressTool.xcodeproj \
            -scheme StressTool \
            -destination 'platform=macOS,arch=x86_64' \
            CODE_SIGNING_ALLOWED=NO | xcpretty && exit ${PIPESTATUS[0]}
            
      - name: Run Tests
        run: |
          xcodebuild test \
            -project StressTool.xcodeproj \
            -scheme StressTool \
            -destination 'platform=macOS,arch=x86_64' \
            CODE_SIGNING_ALLOWED=NO | xcpretty && exit ${PIPESTATUS[0]}
